stocks_profile:
  target: prod
  outputs:
    prod:
      type: postgres
      host: ${POSTGRES_HOST}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      port: ${POSTGRES_PORT}
      dbname: ${POSTGRES_DB}
      schema: analytics
      threads: 4
